### PR TITLE
Changes to support etcd.

### PR DESCRIPTION
**Pull request by Lukasa**
This PR adds changes that support etcd.

I suspect there's additional configuration required for Felix here, so let's not merge this just yet.

### CODE REVIEW

**Comment by Lukasa** [comment]
Alright, I've made some changes to actually get etcd to work. These are currently present on the CI server and have had a few clean runs, and I've tested them myself.

**Comment by Lukasa** [comment]
There's further work needed here to get this to do appropriate configuration of Felix and the plugin. @neiljerram, @plwhite, can one of you take over the ownership of getting Felix and the plugin appropriately configured by the chef scripts?

**Comment by nelljerram** [comment]
Sorry, I've not focussed on this today, and now the people have (nearly) gone who probably know most about it.  What's the situation now, as regards:
- how urgently this is needed for (our etcd integration plan)?
- is anyone already doing Chef installs and handling these steps manually?

Thanks!

**Comment by Lukasa** [comment]
This is needed at the same time as the cutover to master.

**Comment by nelljerram** [comment]
Cool, thanks.  I'll make sure it happens at or about that time.

**Comment by tomdee** [comment]
Closing v. old PR.

**Pull request closed without merging**
